using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Grasshopper.Kernel;
using Rhino.Geometry;

using ShapeGrammar3D.Classes.Elements;
using ShapeGrammar3D.Classes;

namespace ShapeGrammar3D.Classes.Rules
{
    [Serializable]
    public class SG_AutoRule02_3D : SG_Rule
    {
        // --- properties ---
        public List<string> ElemNames { get; set; } = new List<string>();
        public double[] Domain { get; set; }

        // --- constructors ---
        public SG_AutoRule02_3D()
        {
        }

        public SG_AutoRule02_3D(List<string> _eNames, double[] _domain)
        {
            RuleState = State.alpha;
            Name = "SG_AutoRule_02_3D";
            ElemNames = _eNames;
            Domain = _domain;
            RuleMarker = UT.RULE020_MARKER;

        }

        // --- methods ---

        public override void NewRuleParameters(Random random, SG_Shape ss) { }
        public override SG_Rule CopyRule(SG_Rule rule)
        {
            throw new NotImplementedException();
        }
        public override string RuleOperation(ref SG_Shape ss_ref, ref SG_Genotype gt)
        {
            string returnMessage = "";

            // find relevant range in genotype
            int sid = -999;
            int eid = -999;
            List<int> selectedIntGenes;
            List<double> selectedDGenes;

            gt.FindRange(ref sid, ref eid, UT.RULE020_MARKER);

            if (sid == -999 || eid == -999)
            {
                return "SG_AutoRule_02_3D - wrong marker";
            }

            // extract relevant genes
            selectedIntGenes = gt.IntGenes.GetRange(sid, eid - sid);
            selectedDGenes = gt.DGenes.GetRange(sid, eid - sid);

            double range = Domain[1] - Domain[0];

            // remove unused nodes
            ss_ref.UnregisterElemsFromNodes();
            ss_ref.RegisterElemsToNodes();

            // default cross-section
            SH_CrossSection_Rectangle def_crosec = new SH_CrossSection_Rectangle(10, 10);
            def_crosec.Material = (SH_Material) SH_Material_Isotrop.Default_Material();

            for (int i = 0; i < selectedIntGenes.Count; i++)
            {
                if (selectedIntGenes[i] == 0) continue;
                if (i >= ss_ref.Nodes.Count) break;

                if (ss_ref.Nodes[i].Elements.Count == 1
                    && ss_ref.Nodes[i].Elements[0].Autorule == UT.RULE020_MARKER)
                {
                    continue; // 230823 to avoid vertically stacking elements generated by rule2
                }

                double param = selectedDGenes[i];
                param = Clamp(param, 0.0, 1.0); // keep within valid range
                double length = param * range + Domain[0];

                int numStuds = ss_ref.Nodes[i].NumStuds;

                if (Math.Abs(length) >= UT.MIN_SEG_LEN)
                {
                    // ensure a base element from rule 010 exists
                    SG_Elem1D baseElem = ss_ref.Nodes[i].Elements
                        .OfType<SG_Elem1D>()
                        .FirstOrDefault(e => e.Autorule == UT.RULE010_MARKER);
                    if (baseElem == null)
                    {
                        continue; // skip if no supporting element
                    }

                    for (int j = 0; j < numStuds; j++)
                    {
                        Line ln = new Line(ss_ref.Nodes[i].Pt, ss_ref.Nodes[i].NPln.YAxis, length);
                        SG_Elem1D elem = new SG_Elem1D(ln, -999, "3DAR2", def_crosec)
                        {
                            Autorule = UT.RULE020_MARKER
                        };

                        elem.Init_Crv = baseElem.Init_Crv;
                        elem.Nodes[0] = ss_ref.Nodes[i];
                        elem.Nodes[1] = new SG_Node(ln.To, -999);

                        elem.CrossSection = (SH_CrossSection_Beam)def_crosec;

                        SG_Elem1D iniElem = ss_ref.Nodes[i].Elements.OfType<SG_Elem1D>().FirstOrDefault();
                        if (iniElem != null)
                        {
                            elem.Crv = iniElem.Crv;
                        }

                        ss_ref.AddNewElement(elem);
                    }
                }
                else
                {
                    returnMessage += $"line too short: at node {ss_ref.Nodes[i].ID} \n";
                }

            }

            returnMessage += "SG_AutoRule_02_3D successfully applied.";


            return returnMessage;
        }
        public override State GetNextState()
        {
            throw new NotImplementedException();
        }

        private static double Clamp(double value, double min, double max)
        {
            if (value < min) return min;
            if (value > max) return max;
            return value;
        }
    }

}
