using System;
using System.Collections.Generic;
using Grasshopper.Kernel;
using ShapeGrammar3D.Classes;
using ShapeGrammar3D.Classes.Rules;

namespace ShapeGrammar3D.Components.RuleComponents
{
    public class AutoRule012_3D : GH_Component
    {
        public AutoRule012_3D()
          : base("Auto rule 012-3D", "A-Rule012-3D",
              "Moves nodes generated by AutoRule01-3D in Z direction within the given domain.",
              UT.CAT, UT.GR_RLS)
        {
        }

        protected override void RegisterInputParams(GH_InputParamManager pManager)
        {
            pManager.AddTextParameter("Elem Name", "eName", "Element name filter (reserved)", GH_ParamAccess.list);
            pManager.AddNumberParameter("Domain", "Domain", "Z movement domain [min, max]", GH_ParamAccess.list);
        }

        protected override void RegisterOutputParams(GH_OutputParamManager pManager)
        {
            pManager.AddGenericParameter("Rule", "Rule", "Rule", GH_ParamAccess.item);
        }

        protected override void SolveInstance(IGH_DataAccess DA)
        {
            var eNames = new List<string>();
            var domain = new List<double>();

            if (!DA.GetDataList(0, eNames)) return;
            if (!DA.GetDataList(1, domain)) return;
            if (domain.Count < 2)
            {
                AddRuntimeMessage(GH_RuntimeMessageLevel.Error, "Domain requires two values: [min, max].");
                return;
            }

            var rule = new SG_AutoRule012_3D(eNames, domain.ToArray());
            DA.SetData(0, rule);
        }

        protected override System.Drawing.Bitmap Icon => Properties.Resources.icons_Generic;

        public override Guid ComponentGuid => new Guid("3D9B7E2B-A8F4-4E5A-AB53-12E74E8F8A21");
    }
}
